In [2]:
import pandas as pd

In [8]:
pwd

'C:\\Users\\user'

In [3]:
df=pd.read_csv("training.1600000.processed.noemoticon.csv",sep=",")

In [4]:
df

,target,ids,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
5,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
6,0,1467811592,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,mybirch,Need a hug
7,0,1467811594,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,coZZ,@LOLTrish hey long time no see! Yes.. Rains a...
8,0,1467811795,Mon Apr 06 22:20:05 PDT 2009,NO_QUERY,2Hood4Hollywood,@Tatiana_K nope they didn't have it
9,0,1467812025,Mon Apr 06 22:20:09 PDT 2009,NO_QUERY,mimismo,@twittera que me muera ?
10,0,1467812416,Mon Apr 06 22:20:16 PDT 2009,NO_QUERY,erinx3leannexo,spring break in plain city... it's snowing
11,0,1467812579,Mon Apr 06 22:20:17 PDT 2009,NO_QUERY,pardonlauren,I just re-pierced my ears
12,0,1467812723,Mon Apr 06 22:20:19 PDT 2009,NO_QUERY,TLeC,@caregiving I couldn't bear to watch it. And ...
13,0,1467812771,Mon Apr 06 22:20:19 PDT 2009,NO_QUERY,robrobbierobert,"@octolinz16 It it counts, idk why I did either..."
14,0,1467812784,Mon Apr 06 22:20:20 PDT 2009,NO_QUERY,bayofwolves,"@smarrison i would've been the first, but i di..."
15,0,1467812799,Mon Apr 06 22:20:20 PDT 2009,NO_QUERY,HairByJess,@iamjazzyfizzle I wish I got to watch it with ...
16,0,1467812964,Mon Apr 06 22:20:22 PDT 2009,NO_QUERY,lovesongwriter,Hollis' death scene will hurt me severely to w...
17,0,1467813137,Mon Apr 06 22:20:25 PDT 2009,NO_QUERY,armotley,about to file taxes
18,0,1467813579,Mon Apr 06 22:20:31 PDT 2009,NO_QUERY,starkissed,@LettyA ahh ive always wanted to see rent lov...
19,0,1467813782,Mon Apr 06 22:20:34 PDT 2009,NO_QUERY,gi_gi_bee,@FakerPattyPattz Oh dear. Were you drinking ou...
20,0,1467813985,Mon Apr 06 22:20:37 PDT 2009,NO_QUERY,quanvu,@alydesigns i was out most of the day so didn'...
21,0,1467813992,Mon Apr 06 22:20:38 PDT 2009,NO_QUERY,swinspeedx,"one of my friend called me, and asked to meet ..."
22,0,1467814119,Mon Apr 06 22:20:40 PDT 2009,NO_QUERY,cooliodoc,@angry_barista I baked you a cake but I ated it
23,0,1467814180,Mon Apr 06 22:20:40 PDT 2009,NO_QUERY,viJILLante,this week is not going as i had hoped
24,0,1467814192,Mon Apr 06 22:20:41 PDT 2009,NO_QUERY,Ljelli3166,blagh class at 8 tomorrow
25,0,1467814438,Mon Apr 06 22:20:44 PDT 2009,NO_QUERY,ChicagoCubbie,I hate when I have to call and wake people up
26,0,1467814783,Mon Apr 06 22:20:50 PDT 2009,NO_QUERY,KatieAngell,Just going to cry myself to sleep after watchi...
27,0,1467814883,Mon Apr 06 22:20:52 PDT 2009,NO_QUERY,gagoo,im sad now Miss.Lilly
28,0,1467815199,Mon Apr 06 22:20:56 PDT 2009,NO_QUERY,abel209,ooooh.... LOL that leslie.... and ok I won't ...
29,0,1467815753,Mon Apr 06 22:21:04 PDT 2009,NO_QUERY,BaptisteTheFool,Meh... Almost Lover is the exception... this t...
...,...,...,...,...,...,...
1599970,4,2193578196,Tue Jun 16 08:38:54 PDT 2009,NO_QUERY,adbillingsley,Thanks @eastwestchic &amp; @wangyip Thanks! Th...
1599971,4,2193578237,Tue Jun 16 08:38:54 PDT 2009,NO_QUERY,gekkko,@marttn thanks Martin. not the most imaginativ...
1599972,4,2193578269,Tue Jun 16 08:38:54 PDT 2009,NO_QUERY,millerslab,@MikeJonesPhoto Congrats Mike Way to go!
1599973,4,2193578319,Tue Jun 16 08:38:55 PDT 2009,NO_QUERY,luckygeorgeblog,http://twitpic.com/7jp4n - OMG! Office Space.....
1599974,4,2193578345,Tue Jun 16 08:38:55 PDT 2009,NO_QUERY,Kristah_Diggs,@yrclndstnlvr ahaha nooo you were just away fr...
1599975,4,2193578347,Tue Jun 16 08:38:55 PDT 2009,NO_QUERY,CoachChic,"@BizCoachDeb Hey, I'm baack! And, thanks so m..."
1599976,4,2193578348,Tue Jun 16 08:38:55 PDT 2009,NO_QUERY,serianna,"@mattycus Yeah, my conscience would be clear i..."
1599977,4,2193578386,Tue Jun 16 08:38:55 PDT 2009,NO_QUERY,TeamUKskyvixen,@MayorDorisWolfe Thats my girl - dishing out t...
1599978,4,2193578395,Tue Jun 16 08:38:55 PDT 2009,NO_QUERY,LaurenMoo10,@shebbs123 i second that
1599979,4,2193578576,Tue Jun 16 08:38:57 PDT 2009,NO_QUERY,angel_sammy04,In the garden
1599980,4,2193578679,Tue Jun 16 08:38:56 PDT 2009,NO_QUERY,puchal_ek,@myheartandmind jo jen by nemuselo zrovna tÃ© ...
1599981,4,2193578716,Tue Jun 16 08:38:57 PDT 2009,NO_QUERY,youtubelatest,Another Commenting Contest! [;: Yay!!! http:/...
1599982,4,2193578739,Tue Jun 16 08:38:57 PDT 2009,NO_QUERY,Mandi_Davenport,@thrillmesoon i figured out how to see my twee...
1599983,4,2193578758,Tue Jun 16 08:38:57 PDT 2009,NO_QUERY,xoAurixo,"@oxhot theri tomorrow, drinking coffee, talkin..."
1599984,4,2193578847,Tue Jun 16 08:38:57 PDT 2009,NO_QUERY,RobFoxKerr,You heard it here first -- We're having a girl...
1599985,4,2193578982,Tue Jun 16 08:38:58 PDT 2009,NO_QUERY,LISKFEST,"if ur the lead singer in a band, beware fallin..."
1599986,4,2193579087,Tue Jun 16 08:38:58 PDT 2009,NO_QUERY,marhgil,@tarayqueen too much ads on my blog.
1599987,4,2193579092,Tue Jun 16 08:38:58 PDT 2009,NO_QUERY,cathriiin,@La_r_a NEVEER I think that you both will get...
1599988,4,2193579191,Tue Jun 16 08:38:59 PDT 2009,NO_QUERY,tellman,@Roy_Everitt ha- good job. that's right - we g...
1599989,4,2193579211,Tue Jun 16 08:38:59 PDT 2009,NO_QUERY,jazzstixx,@Ms_Hip_Hop im glad ur doing well
1599990,4,2193579249,Tue Jun 16 08:38:59 PDT 2009,NO_QUERY,razzberry5594,WOOOOO! Xbox is back
1599991,4,2193579284,Tue Jun 16 08:38:59 PDT 2009,NO_QUERY,AgustinaP,@rmedina @LaTati Mmmm That sounds absolutely ...
1599992,4,2193579434,Tue Jun 16 08:39:00 PDT 2009,NO_QUERY,sdancingsteph,ReCoVeRiNg FrOm ThE lOnG wEeKeNd
1599993,4,2193579477,Tue Jun 16 08:39:00 PDT 2009,NO_QUERY,ChloeAmisha,@SCOOBY_GRITBOYS
1599994,4,2193579489,Tue Jun 16 08:39:00 PDT 2009,NO_QUERY,EvolveTom,"@Cliff_Forster Yeah, that does work better tha..."
1599995,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 6 columns):
target    1600000 non-null int64
ids       1600000 non-null int64
date      1600000 non-null object
flag      1600000 non-null object
user      1600000 non-null object
text      1600000 non-null object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

In [23]:
import numpy as np
def train_test_split(data,test_ratio):    
    shuffled_indices=np.random.permutation(len(data))
    test_size=int(test_ratio*len(data))
    test_indices=shuffled_indices[:test_size]
    train_indices=shuffled_indices[test_size:]
    return data.iloc[train_indices],data.iloc[test_indices]
train_set,test_set=train_test_split(df,0.2)
print(len(train_set))
print(len(test_set))
train_set.text
test_set.target

1280000
320000

203419     0
1005025    4
972951     4
1434061    4
500204     0
1253582    4
839876     4
42966      0
866596     4
657632     0
227143     0
710523     0
923004     4
600369     0
1281225    4
97220      0
590268     0
1580305    4
1085208    4
672553     0
1032116    4
355830     0
611941     0
870735     4
1062384    4
357779     0
522469     0
13320      0
22737      0
1310840    4
          ..
1311538    4
923156     4
1467022    4
802479     4
554565     0
1584200    4
261265     0
1213940    4
712903     0
210986     0
1218080    4
1129474    4
617891     0
507799     0
400693     0
432474     0
70635      0
1445583    4
225850     0
150460     0
849740     4
1231579    4
349374     0
921965     4
1264993    4
442245     0
393648     0
404414     0
1249542    4
268630     0
Name: target, Length: 320000, dtype: int64

In [21]:
X_train=train_set.text
y_train=train_set.target
X_test=test_set.text
y_test=test_set.target
X_train.head(20)
y_train.head(20)

954891     4
465491     0
202880     0
26257      0
1365675    4
1391472    4
700992     0
1440643    4
539092     0
1387111    4
374291     0
504291     0
685803     0
1277250    4
291395     0
905379     4
1169548    4
1490760    4
1303383    4
920298     4
Name: target, dtype: int64

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()

In [27]:
vect.fit(X_train)
X_train_dtm=vect.transform(X_train)

In [ ]:
X_train_dtm=vect.fit_trasnform(X_train)

In [28]:
X_train_dtm

<1280000x590376 sparse matrix of type '<class 'numpy.int64'>'
	with 15193262 stored elements in Compressed Sparse Row format>

In [29]:
X_test_dtm=vect.transform(X_test)
X_test_dtm

<320000x590376 sparse matrix of type '<class 'numpy.int64'>'
	with 3697153 stored elements in Compressed Sparse Row format>

In [31]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [32]:
%time nb.fit(X_train_dtm,y_train)

Wall time: 2.11 s

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [33]:
y_pred_class=nb.predict(X_test_dtm)

In [35]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)

0.78111875

In [38]:
metrics.confusion_matrix(y_test,y_pred_class)

array([[130995,  29004],
       [ 41038, 118963]], dtype=int64)